//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//
//       bebopc version:
//           3.2.3
//
//
//       bebopc source:
//           https://github.com/6over3/bebop
//
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
import { BebopView, BebopRuntimeError, BebopRecord } from "bebop";
import { Metadata, MethodType } from "@tempojs/common";
import {  BaseClient, MethodInfo, CallOptions } from "@tempojs/client";
import { ServiceRegistry, BaseService, ServerContext, BebopMethodAny, BebopMethod } from "@tempojs/server";

export const BEBOP_SCHEMA = new Uint8Array ([
3, 16, 0, 0, 0, 71, 117, 105, 100, 65, 114, 114, 97, 121,
68, 101, 108, 116, 97, 0, 2, 0, 5, 0, 0, 0, 3, 115, 101,
116, 0, 242, 255, 255, 255, 0, 244, 255, 255, 255, 0, 1,
97, 100, 100, 0, 242, 255, 255, 255, 0, 244, 255, 255,
255, 0, 2, 114, 101, 109, 111, 118, 101, 0, 242, 255, 255,
255, 0, 244, 255, 255, 255, 0, 3, 69, 110, 116, 105, 116,
121, 68, 101, 108, 116, 97, 0, 2, 0, 5, 0, 0, 0, 6, 105,
100, 0, 244, 255, 255, 255, 0, 1, 114, 111, 111, 116, 0,
244, 255, 255, 255, 0, 2, 116, 97, 103, 115, 0, 242, 255,
255, 255, 0, 13, 0, 0, 0, 0, 3, 112, 97, 114, 101, 110,
116, 0, 244, 255, 255, 255, 0, 4, 99, 104, 105, 108, 100,
114, 101, 110, 0, 0, 0, 0, 0, 0, 5, 104, 101, 97, 108,
116, 104, 0, 15, 0, 0, 0, 0, 6, 77, 117, 116, 97, 116,
105, 111, 110, 84, 121, 112, 101, 0, 4, 0, 251, 255, 255,
255, 0, 4, 0, 0, 0, 3, 73, 110, 115, 101, 114, 116, 0, 0,
1, 0, 0, 0, 85, 112, 100, 97, 116, 101, 0, 0, 2, 0, 0, 0,
68, 101, 108, 101, 116, 101, 0, 0, 3, 0, 0, 0, 73, 110,
115, 101, 114, 116, 0, 1, 0, 0, 5, 0, 0, 0, 0, 1, 101,
110, 116, 105, 116, 121, 0, 11, 0, 0, 0, 0, 85, 112, 100,
97, 116, 101, 0, 1, 0, 0, 5, 0, 0, 0, 0, 1, 100, 101, 108,
116, 97, 0, 1, 0, 0, 0, 0, 68, 101, 108, 101, 116, 101, 0,
1, 0, 0, 5, 0, 0, 0, 0, 1, 101, 110, 116, 105, 116, 121,
0, 11, 0, 0, 0, 0, 77, 117, 116, 97, 116, 105, 111, 110,
82, 101, 99, 111, 114, 100, 0, 3, 0, 10, 0, 0, 0, 3, 1, 3,
0, 0, 0, 2, 4, 0, 0, 0, 3, 5, 0, 0, 0, 77, 117, 116, 97,
116, 105, 111, 110, 83, 99, 111, 112, 101, 0, 2, 0, 5, 0,
0, 0, 1, 109, 117, 116, 97, 116, 105, 111, 110, 115, 0,
241, 255, 255, 255, 244, 255, 255, 255, 6, 0, 0, 0, 0, 1,
65, 116, 116, 97, 99, 107, 0, 2, 0, 5, 0, 0, 0, 3, 115,
111, 117, 114, 99, 101, 0, 244, 255, 255, 255, 0, 1, 116,
97, 114, 103, 101, 116, 0, 244, 255, 255, 255, 0, 2, 100,
97, 109, 97, 103, 101, 0, 251, 255, 255, 255, 0, 3, 84,
97, 107, 101, 68, 97, 109, 97, 103, 101, 0, 2, 0, 5, 0, 0,
0, 3, 115, 111, 117, 114, 99, 101, 0, 244, 255, 255, 255,
0, 1, 116, 97, 114, 103, 101, 116, 0, 244, 255, 255, 255,
0, 2, 100, 97, 109, 97, 103, 101, 0, 251, 255, 255, 255,
0, 3, 65, 99, 116, 105, 111, 110, 115, 0, 3, 0, 10, 0, 0,
0, 2, 1, 8, 0, 0, 0, 2, 9, 0, 0, 0, 69, 110, 116, 105,
116, 121, 0, 2, 0, 5, 0, 0, 0, 6, 105, 100, 0, 244, 255,
255, 255, 0, 1, 114, 111, 111, 116, 0, 244, 255, 255, 255,
0, 2, 116, 97, 103, 115, 0, 242, 255, 255, 255, 0, 13, 0,
0, 0, 0, 3, 112, 97, 114, 101, 110, 116, 0, 244, 255, 255,
255, 0, 4, 99, 104, 105, 108, 100, 114, 101, 110, 0, 242,
255, 255, 255, 0, 244, 255, 255, 255, 0, 5, 104, 101, 97,
108, 116, 104, 0, 14, 0, 0, 0, 0, 6, 83, 116, 97, 116,
101, 0, 2, 0, 5, 0, 0, 0, 1, 110, 115, 0, 245, 255, 255,
255, 0, 1, 84, 97, 103, 115, 0, 4, 0, 251, 255, 255, 255,
0, 4, 0, 0, 0, 3, 72, 117, 109, 97, 110, 0, 0, 1, 0, 0, 0,
80, 108, 97, 121, 101, 114, 67, 111, 110, 116, 114, 111,
108, 108, 101, 100, 0, 0, 2, 0, 0, 0, 72, 111, 115, 116,
105, 108, 101, 0, 0, 3, 0, 0, 0, 80, 111, 111, 108, 0, 2,
0, 5, 0, 0, 0, 5, 112, 111, 105, 110, 116, 115, 0, 251,
255, 255, 255, 0, 1, 109, 105, 110, 0, 251, 255, 255, 255,
0, 2, 109, 97, 120, 0, 251, 255, 255, 255, 0, 3, 114, 97,
116, 101, 0, 250, 255, 255, 255, 0, 4, 105, 110, 116, 101,
114, 118, 97, 108, 0, 251, 255, 255, 255, 0, 5, 80, 111,
111, 108, 68, 101, 108, 116, 97, 0, 2, 0, 5, 0, 0, 0, 5,
112, 111, 105, 110, 116, 115, 0, 250, 255, 255, 255, 0, 1,
109, 105, 110, 0, 250, 255, 255, 255, 0, 2, 109, 97, 120,
0, 250, 255, 255, 255, 0, 3, 114, 97, 116, 101, 0, 250,
255, 255, 255, 0, 4, 105, 110, 116, 101, 114, 118, 97,
108, 0, 250, 255, 255, 255, 0, 5, 1, 0, 0, 0, 82, 112, 99,
0, 0, 3, 0, 0, 0, 115, 112, 97, 119, 110, 0, 0, 0, 11, 0,
0, 0, 11, 0, 0, 0, 62, 226, 118, 138, 97, 99, 116, 0, 0,
0, 10, 0, 0, 0, 10, 0, 0, 0, 48, 15, 87, 211, 111, 98,
115, 101, 114, 118, 101, 0, 0, 1, 7, 0, 0, 0, 7, 0, 0, 0,
214, 29, 17, 28
]);

export interface GuidArrayDelta {

  set?: string[];

  add?: string[];

  remove?: string[];
}

export const GuidArrayDelta = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: GuidArrayDelta): GuidArrayDelta & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return GuidArrayDelta.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: GuidArrayDelta): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      GuidArrayDelta.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: GuidArrayDelta, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.set !== undefined) {
        view.writeByte(1);
        {
        const length0 = record.set.length;
        view.writeUint32(length0);
        for (let i0 = 0; i0 < length0; i0++) {
          view.writeGuid(record.set[i0]);
        }
      }
      }
      if (record.add !== undefined) {
        view.writeByte(2);
        {
        const length0 = record.add.length;
        view.writeUint32(length0);
        for (let i0 = 0; i0 < length0; i0++) {
          view.writeGuid(record.add[i0]);
        }
      }
      }
      if (record.remove !== undefined) {
        view.writeByte(3);
        {
        const length0 = record.remove.length;
        view.writeUint32(length0);
        for (let i0 = 0; i0 < length0; i0++) {
          view.writeGuid(record.remove[i0]);
        }
      }
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): GuidArrayDelta & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = GuidArrayDelta.readFrom(view);
      return GuidArrayDelta(decoded);
    },

    readFrom(view: BebopView): GuidArrayDelta {
      const message: GuidArrayDelta = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            {
          const length0 = view.readUint32();
          message.set = [];
          for (let i0 = 0; i0 < length0; i0++) {
            let x0: string;
            x0 = view.readGuid();
            message.set[i0] = x0;
          }
        }
            break;

          case 2:
            {
          const length0 = view.readUint32();
          message.add = [];
          for (let i0 = 0; i0 < length0; i0++) {
            let x0: string;
            x0 = view.readGuid();
            message.add[i0] = x0;
          }
        }
            break;

          case 3:
            {
          const length0 = view.readUint32();
          message.remove = [];
          for (let i0 = 0; i0 < length0; i0++) {
            let x0: string;
            x0 = view.readGuid();
            message.remove[i0] = x0;
          }
        }
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));


export interface EntityDelta {

  id?: string;

  root?: string;

  tags?: Tags[];

  parent?: string;

  children?: GuidArrayDelta;

  health?: PoolDelta;
}

export const EntityDelta = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: EntityDelta): EntityDelta & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return EntityDelta.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: EntityDelta): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      EntityDelta.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: EntityDelta, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.id !== undefined) {
        view.writeByte(1);
        view.writeGuid(record.id);
      }
      if (record.root !== undefined) {
        view.writeByte(2);
        view.writeGuid(record.root);
      }
      if (record.tags !== undefined) {
        view.writeByte(3);
        {
        const length0 = record.tags.length;
        view.writeUint32(length0);
        for (let i0 = 0; i0 < length0; i0++) {
          view.writeUint32(record.tags[i0]);
        }
      }
      }
      if (record.parent !== undefined) {
        view.writeByte(4);
        view.writeGuid(record.parent);
      }
      if (record.children !== undefined) {
        view.writeByte(5);
        GuidArrayDelta.encodeInto(record.children, view);
      }
      if (record.health !== undefined) {
        view.writeByte(6);
        PoolDelta.encodeInto(record.health, view);
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): EntityDelta & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = EntityDelta.readFrom(view);
      return EntityDelta(decoded);
    },

    readFrom(view: BebopView): EntityDelta {
      const message: EntityDelta = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            message.id = view.readGuid();
            break;

          case 2:
            message.root = view.readGuid();
            break;

          case 3:
            {
          const length0 = view.readUint32();
          message.tags = [];
          for (let i0 = 0; i0 < length0; i0++) {
            let x0: Tags;
            x0 = view.readUint32();
            message.tags[i0] = x0;
          }
        }
            break;

          case 4:
            message.parent = view.readGuid();
            break;

          case 5:
            message.children = GuidArrayDelta.readFrom(view);
            break;

          case 6:
            message.health = PoolDelta.readFrom(view);
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));


export enum MutationType {

  Insert = 1,

  Update = 2,

  Delete = 3,
}


export interface Insert {

  readonly entity: Entity;
}

export const Insert = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: Insert): Insert & BebopRecord => {
    return Object.freeze({
      ...data,
      encode(): Uint8Array {
        return Insert.encode(this);
      }
    });
  },
  // Static methods
  {
    encode(record: Insert): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      Insert.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: Insert, view: BebopView): void {
      Entity.encodeInto(record.entity, view);
    },

    decode(buffer: Uint8Array): Insert & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = Insert.readFrom(view);
      return Insert(decoded);
    },

    readFrom(view: BebopView): Insert {
      let field0: Entity;
      field0 = Entity.readFrom(view);
      return {
        entity: field0,
      };
    },
  }
));


export interface Update {

  readonly delta: EntityDelta;
}

export const Update = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: Update): Update & BebopRecord => {
    return Object.freeze({
      ...data,
      encode(): Uint8Array {
        return Update.encode(this);
      }
    });
  },
  // Static methods
  {
    encode(record: Update): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      Update.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: Update, view: BebopView): void {
      EntityDelta.encodeInto(record.delta, view);
    },

    decode(buffer: Uint8Array): Update & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = Update.readFrom(view);
      return Update(decoded);
    },

    readFrom(view: BebopView): Update {
      let field0: EntityDelta;
      field0 = EntityDelta.readFrom(view);
      return {
        delta: field0,
      };
    },
  }
));


export interface Delete {

  readonly entity: Entity;
}

export const Delete = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: Delete): Delete & BebopRecord => {
    return Object.freeze({
      ...data,
      encode(): Uint8Array {
        return Delete.encode(this);
      }
    });
  },
  // Static methods
  {
    encode(record: Delete): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      Delete.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: Delete, view: BebopView): void {
      Entity.encodeInto(record.entity, view);
    },

    decode(buffer: Uint8Array): Delete & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = Delete.readFrom(view);
      return Delete(decoded);
    },

    readFrom(view: BebopView): Delete {
      let field0: Entity;
      field0 = Entity.readFrom(view);
      return {
        entity: field0,
      };
    },
  }
));


export type MutationRecord = { tag: 1, value: Insert } | { tag: 2, value: Update } | { tag: 3, value: Delete };

export const MutationRecord = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: MutationRecord): MutationRecord & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return MutationRecord.encode(this);
      }
    };
  },
  // Static methods
  {
    fromInsert(value: Insert): MutationRecord & BebopRecord {
      return MutationRecord({ tag: 1, value });
    },

    fromUpdate(value: Update): MutationRecord & BebopRecord {
      return MutationRecord({ tag: 2, value });
    },

    fromDelete(value: Delete): MutationRecord & BebopRecord {
      return MutationRecord({ tag: 3, value });
    },

    encode(record: MutationRecord): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      MutationRecord.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: MutationRecord, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length + 1;
      view.writeByte(record.tag);
      switch (record.tag) {
        case 1:
          Insert.encodeInto(record.value, view);
          break;
        case 2:
          Update.encodeInto(record.value, view);
          break;
        case 3:
          Delete.encodeInto(record.value, view);
          break;
      }
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): MutationRecord & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = MutationRecord.readFrom(view);
      return MutationRecord(decoded);
    },

    readFrom(view: BebopView): MutationRecord {
      const length = view.readMessageLength();
      const end = view.index + 1 + length;
      const tag = view.readByte();
      switch (tag) {
        case 1:
          return { tag: 1, value: Insert.readFrom(view) };
        case 2:
          return { tag: 2, value: Update.readFrom(view) };
        case 3:
          return { tag: 3, value: Delete.readFrom(view) };
        default:
          view.index = end;
          throw new BebopRuntimeError(`Unknown union discriminator: ${tag}`);
      }
    },
  }
));


export interface MutationScope {

  mutations?: Map<string, MutationRecord>;
}

export const MutationScope = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: MutationScope): MutationScope & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return MutationScope.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: MutationScope): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      MutationScope.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: MutationScope, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.mutations !== undefined) {
        view.writeByte(1);
        view.writeUint32(record.mutations.size);
      for (const [k0, v0] of record.mutations) {
        view.writeGuid(k0);
        MutationRecord.encodeInto(v0, view);
      }
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): MutationScope & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = MutationScope.readFrom(view);
      return MutationScope(decoded);
    },

    readFrom(view: BebopView): MutationScope {
      const message: MutationScope = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            {
          const length0 = view.readUint32();
          message.mutations = new Map();
          for (let i0 = 0; i0 < length0; i0++) {
            let k0: string;
            let v0: MutationRecord;
            k0 = view.readGuid();
            v0 = MutationRecord.readFrom(view);
            message.mutations.set(k0, v0);
          }
        }
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));


export interface Attack {

  source?: string;

  target?: string;

  damage?: number;
}

export const Attack = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: Attack): Attack & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return Attack.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: Attack): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      Attack.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: Attack, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.source !== undefined) {
        view.writeByte(1);
        view.writeGuid(record.source);
      }
      if (record.target !== undefined) {
        view.writeByte(2);
        view.writeGuid(record.target);
      }
      if (record.damage !== undefined) {
        view.writeByte(3);
        view.writeUint32(record.damage);
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): Attack & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = Attack.readFrom(view);
      return Attack(decoded);
    },

    readFrom(view: BebopView): Attack {
      const message: Attack = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            message.source = view.readGuid();
            break;

          case 2:
            message.target = view.readGuid();
            break;

          case 3:
            message.damage = view.readUint32();
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));


export interface TakeDamage {

  source?: string;

  target?: string;

  damage?: number;
}

export const TakeDamage = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: TakeDamage): TakeDamage & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return TakeDamage.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: TakeDamage): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      TakeDamage.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: TakeDamage, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.source !== undefined) {
        view.writeByte(1);
        view.writeGuid(record.source);
      }
      if (record.target !== undefined) {
        view.writeByte(2);
        view.writeGuid(record.target);
      }
      if (record.damage !== undefined) {
        view.writeByte(3);
        view.writeUint32(record.damage);
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): TakeDamage & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = TakeDamage.readFrom(view);
      return TakeDamage(decoded);
    },

    readFrom(view: BebopView): TakeDamage {
      const message: TakeDamage = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            message.source = view.readGuid();
            break;

          case 2:
            message.target = view.readGuid();
            break;

          case 3:
            message.damage = view.readUint32();
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));


export type Actions = { tag: 1, value: Attack } | { tag: 2, value: TakeDamage };

export const Actions = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: Actions): Actions & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return Actions.encode(this);
      }
    };
  },
  // Static methods
  {
    fromAttack(value: Attack): Actions & BebopRecord {
      return Actions({ tag: 1, value });
    },

    fromTakeDamage(value: TakeDamage): Actions & BebopRecord {
      return Actions({ tag: 2, value });
    },

    encode(record: Actions): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      Actions.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: Actions, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length + 1;
      view.writeByte(record.tag);
      switch (record.tag) {
        case 1:
          Attack.encodeInto(record.value, view);
          break;
        case 2:
          TakeDamage.encodeInto(record.value, view);
          break;
      }
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): Actions & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = Actions.readFrom(view);
      return Actions(decoded);
    },

    readFrom(view: BebopView): Actions {
      const length = view.readMessageLength();
      const end = view.index + 1 + length;
      const tag = view.readByte();
      switch (tag) {
        case 1:
          return { tag: 1, value: Attack.readFrom(view) };
        case 2:
          return { tag: 2, value: TakeDamage.readFrom(view) };
        default:
          view.index = end;
          throw new BebopRuntimeError(`Unknown union discriminator: ${tag}`);
      }
    },
  }
));



export interface Entity {

  id?: string;

  root?: string;

  tags?: Tags[];

  parent?: string;

  children?: string[];

  health?: Pool;
}

export const Entity = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: Entity): Entity & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return Entity.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: Entity): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      Entity.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: Entity, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.id !== undefined) {
        view.writeByte(1);
        view.writeGuid(record.id);
      }
      if (record.root !== undefined) {
        view.writeByte(2);
        view.writeGuid(record.root);
      }
      if (record.tags !== undefined) {
        view.writeByte(3);
        {
        const length0 = record.tags.length;
        view.writeUint32(length0);
        for (let i0 = 0; i0 < length0; i0++) {
          view.writeUint32(record.tags[i0]);
        }
      }
      }
      if (record.parent !== undefined) {
        view.writeByte(4);
        view.writeGuid(record.parent);
      }
      if (record.children !== undefined) {
        view.writeByte(5);
        {
        const length0 = record.children.length;
        view.writeUint32(length0);
        for (let i0 = 0; i0 < length0; i0++) {
          view.writeGuid(record.children[i0]);
        }
      }
      }
      if (record.health !== undefined) {
        view.writeByte(6);
        Pool.encodeInto(record.health, view);
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): Entity & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = Entity.readFrom(view);
      return Entity(decoded);
    },

    readFrom(view: BebopView): Entity {
      const message: Entity = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            message.id = view.readGuid();
            break;

          case 2:
            message.root = view.readGuid();
            break;

          case 3:
            {
          const length0 = view.readUint32();
          message.tags = [];
          for (let i0 = 0; i0 < length0; i0++) {
            let x0: Tags;
            x0 = view.readUint32();
            message.tags[i0] = x0;
          }
        }
            break;

          case 4:
            message.parent = view.readGuid();
            break;

          case 5:
            {
          const length0 = view.readUint32();
          message.children = [];
          for (let i0 = 0; i0 < length0; i0++) {
            let x0: string;
            x0 = view.readGuid();
            message.children[i0] = x0;
          }
        }
            break;

          case 6:
            message.health = Pool.readFrom(view);
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));


export interface State {

  ns?: string;
}

export const State = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: State): State & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return State.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: State): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      State.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: State, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.ns !== undefined) {
        view.writeByte(1);
        view.writeString(record.ns);
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): State & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = State.readFrom(view);
      return State(decoded);
    },

    readFrom(view: BebopView): State {
      const message: State = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            message.ns = view.readString();
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));


export enum Tags {

  Human = 1,

  PlayerControlled = 2,

  Hostile = 3,
}


export interface Pool {

  points?: number;

  min?: number;

  max?: number;

  rate?: number;

  interval?: number;
}

export const Pool = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: Pool): Pool & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return Pool.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: Pool): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      Pool.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: Pool, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.points !== undefined) {
        view.writeByte(1);
        view.writeUint32(record.points);
      }
      if (record.min !== undefined) {
        view.writeByte(2);
        view.writeUint32(record.min);
      }
      if (record.max !== undefined) {
        view.writeByte(3);
        view.writeUint32(record.max);
      }
      if (record.rate !== undefined) {
        view.writeByte(4);
        view.writeInt32(record.rate);
      }
      if (record.interval !== undefined) {
        view.writeByte(5);
        view.writeUint32(record.interval);
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): Pool & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = Pool.readFrom(view);
      return Pool(decoded);
    },

    readFrom(view: BebopView): Pool {
      const message: Pool = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            message.points = view.readUint32();
            break;

          case 2:
            message.min = view.readUint32();
            break;

          case 3:
            message.max = view.readUint32();
            break;

          case 4:
            message.rate = view.readInt32();
            break;

          case 5:
            message.interval = view.readUint32();
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));


export interface PoolDelta {

  points?: number;

  min?: number;

  max?: number;

  rate?: number;

  interval?: number;
}

export const PoolDelta = /*#__PURE__*/ Object.freeze(/*#__PURE__*/ Object.assign(
  // Factory function
  (data: PoolDelta): PoolDelta & BebopRecord => {
    return {
      ...data,
      encode(): Uint8Array {
        return PoolDelta.encode(this);
      }
    };
  },
  // Static methods
  {
    encode(record: PoolDelta): Uint8Array {
      const view = BebopView.getInstance();
      view.startWriting();
      PoolDelta.encodeInto(record, view);
      return view.toArray();
    },

    encodeInto(record: PoolDelta, view: BebopView): void {
      const pos = view.reserveMessageLength();
      const start = view.length;
      if (record.points !== undefined) {
        view.writeByte(1);
        view.writeInt32(record.points);
      }
      if (record.min !== undefined) {
        view.writeByte(2);
        view.writeInt32(record.min);
      }
      if (record.max !== undefined) {
        view.writeByte(3);
        view.writeInt32(record.max);
      }
      if (record.rate !== undefined) {
        view.writeByte(4);
        view.writeInt32(record.rate);
      }
      if (record.interval !== undefined) {
        view.writeByte(5);
        view.writeInt32(record.interval);
      }
      view.writeByte(0);
      const end = view.length;
      view.fillMessageLength(pos, end - start);
    },

    decode(buffer: Uint8Array): PoolDelta & BebopRecord {
      const view = BebopView.getInstance();
      view.startReading(buffer);
      const decoded = PoolDelta.readFrom(view);
      return PoolDelta(decoded);
    },

    readFrom(view: BebopView): PoolDelta {
      const message: PoolDelta = {};
      const length = view.readMessageLength();
      const end = view.index + length;
      while (true) {
        switch (view.readByte()) {
          case 0:
            return message;

          case 1:
            message.points = view.readInt32();
            break;

          case 2:
            message.min = view.readInt32();
            break;

          case 3:
            message.max = view.readInt32();
            break;

          case 4:
            message.rate = view.readInt32();
            break;

          case 5:
            message.interval = view.readInt32();
            break;

          default:
            view.index = end;
            return message;
        }
      }
    },
  }
));

export abstract class BaseRpcService extends BaseService {
  public static readonly serviceName = 'RpcService';
  public abstract spawn(record: Entity, context: ServerContext): Promise<Entity>;
  public abstract act(record: Actions, context: ServerContext): Promise<Actions>;
  public abstract observe(record: MutationScope, context: ServerContext): AsyncGenerator<MutationScope, void, undefined>;
}

export class TempoServiceRegistry extends ServiceRegistry {
  private static readonly staticServiceInstances: Map<string, BaseService> = new Map<string, BaseService>();
  public static register(serviceName: string) {
    return (constructor: Function) => {
      const service = Reflect.construct(constructor, [undefined]);
      if (TempoServiceRegistry.staticServiceInstances.has(serviceName)) {
        throw new BebopRuntimeError(`Duplicate service registered: ${serviceName}`);
      }
      TempoServiceRegistry.staticServiceInstances.set(serviceName, service);
    }
  }
  public static tryGetService(serviceName: string): BaseService {
    const service = TempoServiceRegistry.staticServiceInstances.get(serviceName);
    if (service === undefined) {
      throw new BebopRuntimeError(`Unable to retreive service '${serviceName}' - it is not registered.`);
    }
    return service;
  }

  public init(): void {
    let service: BaseService;
    let serviceName: string;
    serviceName = 'RpcService';
    service = TempoServiceRegistry.tryGetService(serviceName);
    if (!(service instanceof BaseRpcService)) {
      throw new BebopRuntimeError(`No service named '${serviceName}'was registered with the TempoServiceRegistry`);
    }
    service.setLogger(this.logger.clone(serviceName));
    TempoServiceRegistry.staticServiceInstances.delete(serviceName);
    this.serviceInstances.push(service);
    if (this.methods.has(2323046974)) {
      const conflictService = this.methods.get(2323046974)!;
      throw new BebopRuntimeError(`RpcService.spawn collides with ${conflictService.service}.${conflictService.name}`)
    }
    this.methods.set(2323046974, {
      name: 'spawn',
      service: serviceName,
      invoke: service.spawn,
      serialize: Entity.encode,
      deserialize: Entity.decode,
      type: MethodType.Unary,
    } as BebopMethod<Entity, Entity>);
    if (this.methods.has(3545698096)) {
      const conflictService = this.methods.get(3545698096)!;
      throw new BebopRuntimeError(`RpcService.act collides with ${conflictService.service}.${conflictService.name}`)
    }
    this.methods.set(3545698096, {
      name: 'act',
      service: serviceName,
      invoke: service.act,
      serialize: Actions.encode,
      deserialize: Actions.decode,
      type: MethodType.Unary,
    } as BebopMethod<Actions, Actions>);
    if (this.methods.has(470883798)) {
      const conflictService = this.methods.get(470883798)!;
      throw new BebopRuntimeError(`RpcService.observe collides with ${conflictService.service}.${conflictService.name}`)
    }
    this.methods.set(470883798, {
      name: 'observe',
      service: serviceName,
      invoke: service.observe,
      serialize: MutationScope.encode,
      deserialize: MutationScope.decode,
      type: MethodType.ServerStream,
    } as BebopMethod<MutationScope, MutationScope>);
  }

  getMethod(id: number): BebopMethodAny | undefined {
    return this.methods.get(id);
  }
}

export interface IRpcClient {

  spawn(request: Entity): Promise<Entity>;
  spawn(request: Entity, metadata: Metadata): Promise<Entity>;

  act(request: Actions): Promise<Actions>;
  act(request: Actions, metadata: Metadata): Promise<Actions>;

  observe(request: MutationScope): Promise<AsyncGenerator<MutationScope, void, undefined>>;
  observe(request: MutationScope, metadata: Metadata): Promise<AsyncGenerator<MutationScope, void, undefined>>;
}


export class RpcClient extends BaseClient implements IRpcClient {
  private static readonly spawnMethodInfo: MethodInfo<Entity, Entity> = {
    name: 'spawn',
    service: 'RpcService',
    id: 2323046974,
    serialize: Entity.encode,
    deserialize: Entity.decode,
    type: MethodType.Unary,
  }

  async spawn(request: Entity): Promise<Entity>;
  async spawn(request: Entity, options: CallOptions): Promise<Entity>;
  async spawn(request: Entity, options?: CallOptions): Promise<Entity> {
    return await this.channel.startUnary(request, this.getContext(), RpcClient.spawnMethodInfo, options);
  }
  private static readonly actMethodInfo: MethodInfo<Actions, Actions> = {
    name: 'act',
    service: 'RpcService',
    id: 3545698096,
    serialize: Actions.encode,
    deserialize: Actions.decode,
    type: MethodType.Unary,
  }

  async act(request: Actions): Promise<Actions>;
  async act(request: Actions, options: CallOptions): Promise<Actions>;
  async act(request: Actions, options?: CallOptions): Promise<Actions> {
    return await this.channel.startUnary(request, this.getContext(), RpcClient.actMethodInfo, options);
  }
  private static readonly observeMethodInfo: MethodInfo<MutationScope, MutationScope> = {
    name: 'observe',
    service: 'RpcService',
    id: 470883798,
    serialize: MutationScope.encode,
    deserialize: MutationScope.decode,
    type: MethodType.ServerStream,
  }

  async observe(request: MutationScope): Promise<AsyncGenerator<MutationScope, void, undefined>>;
  async observe(request: MutationScope, options: CallOptions): Promise<AsyncGenerator<MutationScope, void, undefined>>;
  async observe(request: MutationScope, options?: CallOptions): Promise<AsyncGenerator<MutationScope, void, undefined>> {
    return await this.channel.startServerStream(request, this.getContext(), RpcClient.observeMethodInfo, options);
  }
}
