// This file is auto-generated by @vampgg/cli. Do not edit manually.
// Barrel over the generated ECS surface. Import the pure core file directly
// (`./game.core.generated.js`) from non-Worker code to avoid pulling in @vampgg/worker
// and its `cloudflare:workers` import.
export * from "./game.core.generated.js";
export * from "./game.worker.generated.js";
