// This file is auto-generated by @vamp/config. Do not edit manually.
import type { ECSOptions } from "@vamp/ecs";
import { ECSDurableObject, ECSStorage, type RPCContext } from "@vamp/worker";
import type { Entity, Actions, Tags, PoolDelta } from "./bebop";

export const components = { id: 0, root: 1, parent: 3, children: 4, health: 5 } as const satisfies Record<keyof Omit<Entity, "tags">, number>;

export type EntityDelta = {
  id?: string;
  root?: string;
  tags?: Tags[];
  parent?: string;
  children?: { set?: string[]; add?: string[]; remove?: string[] };
  health?: PoolDelta;
};

function applyPoolDelta<T>(base: T, delta: Record<string, number>): T {
  const result = { ...base } as Record<string, number>;
  for (const key in delta) {
    if (delta[key] !== undefined) {
      result[key] = (result[key] ?? 0) + delta[key];
    }
  }
  return result as unknown as T;
}

export function materializeDelta(delta: EntityDelta, base?: Partial<Entity>): Entity {
  return {
    id: delta.id ?? base?.id ?? '',
    root: delta.root ?? base?.root ?? '',
    tags: delta.tags ?? base?.tags ?? [],
    parent: delta.parent ?? base?.parent ?? '',
    children: delta.children?.set ?? base?.children ?? [],
    health: delta.health ? applyPoolDelta(base?.health ?? { points: 0, min: 0, max: 0, rate: 0, interval: 0 }, delta.health as Record<string, number>) : base?.health ?? { points: 0, min: 0, max: 0, rate: 0, interval: 0 },
  } as Entity;
}

export function mergeDelta(entity: Entity, delta: EntityDelta): void {
  if (delta.id !== undefined) entity.id = delta.id;
  if (delta.root !== undefined) entity.root = delta.root;
  if (delta.tags !== undefined) entity.tags = delta.tags;
  if (delta.parent !== undefined) entity.parent = delta.parent;
  if (delta.children) {
    if (delta.children.set) {
      entity.children = delta.children.set;
    } else {
      if (!entity.children) entity.children = [];
      if (delta.children.add) {
        for (const item of delta.children.add) {
          if (!entity.children.includes(item)) entity.children.push(item);
        }
      }
      if (delta.children.remove) {
        entity.children = entity.children.filter((item) => !delta.children!.remove!.includes(item));
      }
    }
  }
  if (delta.health) {
    if (!entity.health) entity.health = {} as any;
    const t = entity.health as Record<string, number>;
    const d = delta.health as Record<string, number>;
    for (const key in d) {
      if (d[key] !== undefined) t[key] = (t[key] ?? 0) + d[key];
    }
  }
}

export function accumulateDelta(from: EntityDelta, to: EntityDelta): EntityDelta {
  if (from.id !== undefined) to.id = from.id;
  if (from.root !== undefined) to.root = from.root;
  if (from.tags !== undefined) to.tags = from.tags;
  if (from.parent !== undefined) to.parent = from.parent;
  if (from.children) {
    if (from.children.set) {
      to.children = from.children;
    } else {
      if (!to.children) to.children = {};
      if (from.children.add) {
        to.children.add = [...(to.children.add ?? []), ...from.children.add];
      }
      if (from.children.remove) {
        to.children.remove = [...(to.children.remove ?? []), ...from.children.remove];
      }
    }
  }
  if (from.health) {
    if (!to.health) {
      to.health = { ...from.health };
    } else {
      const t = to.health as Record<string, number>;
      const d = from.health as Record<string, number>;
      for (const key in d) {
        if (d[key] !== undefined) t[key] = (t[key] ?? 0) + d[key];
      }
    }
  }
  return to;
}

export function createECSOptions(createId: () => string): ECSOptions<Entity, EntityDelta> {
  return { createId, components, materializeDelta, mergeDelta, accumulateDelta };
}

export class GameECS<
    UserSession extends {} = {},
    Context extends {} = {},
    UpdateArguments extends Array<unknown> = [],
  > extends ECSDurableObject<
    UserSession,
    Context,
    UpdateArguments,
    Actions,
    Tags,
    Entity,
    EntityDelta,
    Cloudflare.Env
  > {}

export class GameStorage extends ECSStorage<Entity> {}

export type GameContext<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = RPCContext<UserSession, Context, UpdateArguments, Actions, Tags, Entity, EntityDelta>;
