// This file is auto-generated by @vampgg/cli. Do not edit manually.
import type { MutationBatch } from "@vampgg/ecs";
import { defineECSRuntime, ECSDurableObject, ECSStorage, type ECSRuntimeConfiguration, type RPCContext } from "@vampgg/worker";
import { createInterestBroadcast, type InterestBroadcastConfig } from "@vampgg/worker/interest";
import type { Entity, Actions, Tags } from "./bebop.js";
import { MutationScope, type MutationRecord } from "./bebop.js";
import type { EntityDelta } from "./game.core.generated.js";

/**
 * App-typed {@link ECSDurableObject}: this schema's `Actions`/`Tags`/`Entity`/
 * `EntityDelta` are baked in, leaving `UserSession`/`Context`/`UpdateArguments`/`Env`
 * open (`Env` defaults to `Cloudflare.Env`, configurable via the `env` field in vamp.json).
 * Subclass this as your game's durable object.
 */
export class GameECS<
    UserSession extends {} = {},
    Context extends {} = {},
    UpdateArguments extends Array<unknown> = [],
    Env = Cloudflare.Env,
  > extends ECSDurableObject<
    UserSession,
    Context,
    UpdateArguments,
    Actions,
    Tags,
    Entity,
    EntityDelta,
    Env
  > {}

/** App-typed {@link ECSStorage} over this schema's {@link Entity}. */
export class GameStorage extends ECSStorage<Entity> {}

/**
 * Server environment handed to RPC methods, app-typed for this schema. Retrieve
 * it inside a method with `const [ecs, ws] = ctx.getEnvironment<GameContext>()` —
 * the `[ECS, WebSocket]` tuple carrying the live world.
 */
export type GameContext<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = RPCContext<UserSession, Context, UpdateArguments, Actions, Tags, Entity, EntityDelta>;

/** App-typed {@link ECSRuntimeConfiguration} — the worker runtime config with this schema's types baked in. */
export type GameECSRuntimeConfiguration<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = ECSRuntimeConfiguration<UserSession, Context, UpdateArguments, Actions, Tags, Entity, EntityDelta>;

/** Factory returning a {@link GameECSRuntimeConfiguration}; pass it to {@link defineGameECSRuntime}. */
export type GameECSRuntimeProvider<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = () => GameECSRuntimeConfiguration<UserSession, Context, UpdateArguments>;

/**
 * Register the worker's runtime provider with call-site type safety on `ecs`,
 * `context`, `registerSystems`, `tickArgs`, and `broadcastTick`. Call once from
 * the worker entry.
 */
export function defineGameECSRuntime<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
>(provider: GameECSRuntimeProvider<UserSession, Context, UpdateArguments>): void {
  defineECSRuntime(provider);
}

/**
 * Interest-managed mutation broadcast bound to this schema. Supplies the bebop
 * `encodeBatch` codec and a first-key `resolveViewer` default; pass `canSee` to
 * scope what each observer sees, or omit `config` for a global broadcast.
 */
export function createGameInterestBroadcast<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
>(
  config: Partial<
    InterestBroadcastConfig<
      GameContext<UserSession, Context, UpdateArguments>[0],
      MutationScope,
      Entity,
      EntityDelta
    >
  > = {},
) {
  return createInterestBroadcast<
    GameContext<UserSession, Context, UpdateArguments>[0],
    MutationScope,
    MutationScope,
    Entity,
    EntityDelta
  >({
    encodeBatch: (batch: MutationBatch<Entity, EntityDelta>): Uint8Array =>
      new Uint8Array(
        MutationScope.encode(
          MutationScope({ mutations: batch as unknown as Map<string, MutationRecord> }),
        ),
      ),
    resolveViewer: (record: MutationScope): string | undefined => {
      if (!record.mutations) return undefined;
      for (const key of record.mutations.keys()) return key;
      return undefined;
    },
    ...config,
  });
}
