// This file is auto-generated by @vamp/config. Do not edit manually.
import type { ECSOptions, MutationBatch, EntitySystem, ArchetypeSystem, Behavior, System, Query, QueryBuilder } from "@vamp/ecs";
import { createEntitySystem, createArchetypeSystem, createBehavior } from "@vamp/ecs";
import { applyArrayDelta, accumulateArrayDelta, applyPoolDelta, accumulatePoolDelta } from "@vamp/ecs";
import { defineECSRuntime, ECSDurableObject, ECSStorage, type ECSRuntimeConfiguration, type RPCContext } from "@vamp/worker";
import { createInterestBroadcast, type InterestBroadcastConfig } from "@vamp/worker/interest";
import type { Entity, Actions, Tags, PoolDelta, Vec2Delta } from "./bebop";
import { MutationScope, type MutationRecord } from "./bebop";

export const components = { id: 1, root: 2, parent: 4, children: 5, health: 6, position: 7, velocity: 8, mana: 9, stamina: 10, level: 11, xp: 12, faction: 13 } as const satisfies Record<keyof Omit<Entity, "tags">, number>;

export type EntityDelta = {
  id?: string;
  root?: string;
  tags?: Tags[];
  parent?: string;
  children?: { set?: string[]; add?: string[]; remove?: string[] };
  health?: PoolDelta;
  position?: Vec2Delta;
  velocity?: Vec2Delta;
  mana?: PoolDelta;
  stamina?: PoolDelta;
  level?: number;
  xp?: number;
  faction?: number;
};

export function materializeDelta(delta: EntityDelta, base?: Partial<Entity>): Entity {
  return {
    id: delta.id ?? base?.id ?? '',
    root: delta.root ?? base?.root ?? '',
    tags: delta.tags ?? base?.tags ?? [],
    parent: delta.parent ?? base?.parent ?? '',
    children: applyArrayDelta(base?.children ?? [], delta.children),
    health: delta.health ? applyPoolDelta(base?.health ?? { points: 0, min: 0, max: 0, rate: 0, interval: 0 }, delta.health as Record<string, number>) : base?.health ?? { points: 0, min: 0, max: 0, rate: 0, interval: 0 },
    position: delta.position ? applyPoolDelta(base?.position ?? { x: 0, y: 0 }, delta.position as Record<string, number>) : base?.position ?? { x: 0, y: 0 },
    velocity: delta.velocity ? applyPoolDelta(base?.velocity ?? { x: 0, y: 0 }, delta.velocity as Record<string, number>) : base?.velocity ?? { x: 0, y: 0 },
    mana: delta.mana ? applyPoolDelta(base?.mana ?? { points: 0, min: 0, max: 0, rate: 0, interval: 0 }, delta.mana as Record<string, number>) : base?.mana ?? { points: 0, min: 0, max: 0, rate: 0, interval: 0 },
    stamina: delta.stamina ? applyPoolDelta(base?.stamina ?? { points: 0, min: 0, max: 0, rate: 0, interval: 0 }, delta.stamina as Record<string, number>) : base?.stamina ?? { points: 0, min: 0, max: 0, rate: 0, interval: 0 },
    level: delta.level ?? base?.level ?? 0,
    xp: delta.xp ?? base?.xp ?? 0,
    faction: delta.faction ?? base?.faction ?? 0,
  } as Entity;
}

export function mergeDelta(entity: Entity, delta: EntityDelta): void {
  if (delta.id !== undefined) entity.id = delta.id;
  if (delta.root !== undefined) entity.root = delta.root;
  if (delta.tags !== undefined) entity.tags = delta.tags;
  if (delta.parent !== undefined) entity.parent = delta.parent;
  if (delta.children) entity.children = applyArrayDelta(entity.children ?? [], delta.children);
  if (delta.health) entity.health = applyPoolDelta((entity.health ?? {}) as Record<string, number>, delta.health as Record<string, number>) as Entity["health"];
  if (delta.position) entity.position = applyPoolDelta((entity.position ?? {}) as Record<string, number>, delta.position as Record<string, number>) as Entity["position"];
  if (delta.velocity) entity.velocity = applyPoolDelta((entity.velocity ?? {}) as Record<string, number>, delta.velocity as Record<string, number>) as Entity["velocity"];
  if (delta.mana) entity.mana = applyPoolDelta((entity.mana ?? {}) as Record<string, number>, delta.mana as Record<string, number>) as Entity["mana"];
  if (delta.stamina) entity.stamina = applyPoolDelta((entity.stamina ?? {}) as Record<string, number>, delta.stamina as Record<string, number>) as Entity["stamina"];
  if (delta.level !== undefined) entity.level = delta.level;
  if (delta.xp !== undefined) entity.xp = delta.xp;
  if (delta.faction !== undefined) entity.faction = delta.faction;
}

export function accumulateDelta(from: EntityDelta, to: EntityDelta): EntityDelta {
  if (from.id !== undefined) to.id = from.id;
  if (from.root !== undefined) to.root = from.root;
  if (from.tags !== undefined) to.tags = from.tags;
  if (from.parent !== undefined) to.parent = from.parent;
  if (from.children) to.children = accumulateArrayDelta(to.children, from.children);
  if (from.health) to.health = accumulatePoolDelta(to.health as Record<string, number> | undefined, from.health as Record<string, number>) as EntityDelta["health"];
  if (from.position) to.position = accumulatePoolDelta(to.position as Record<string, number> | undefined, from.position as Record<string, number>) as EntityDelta["position"];
  if (from.velocity) to.velocity = accumulatePoolDelta(to.velocity as Record<string, number> | undefined, from.velocity as Record<string, number>) as EntityDelta["velocity"];
  if (from.mana) to.mana = accumulatePoolDelta(to.mana as Record<string, number> | undefined, from.mana as Record<string, number>) as EntityDelta["mana"];
  if (from.stamina) to.stamina = accumulatePoolDelta(to.stamina as Record<string, number> | undefined, from.stamina as Record<string, number>) as EntityDelta["stamina"];
  if (from.level !== undefined) to.level = from.level;
  if (from.xp !== undefined) to.xp = from.xp;
  if (from.faction !== undefined) to.faction = from.faction;
  return to;
}

export function createECSOptions(createId: () => string): ECSOptions<Entity, EntityDelta> {
  return { createId, components, materializeDelta, mergeDelta, accumulateDelta };
}

export class GameECS<
    UserSession extends {} = {},
    Context extends {} = {},
    UpdateArguments extends Array<unknown> = [],
  > extends ECSDurableObject<
    UserSession,
    Context,
    UpdateArguments,
    Actions,
    Tags,
    Entity,
    EntityDelta,
    Cloudflare.Env
  > {}

export class GameStorage extends ECSStorage<Entity> {}

export type GameContext<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = RPCContext<UserSession, Context, UpdateArguments, Actions, Tags, Entity, EntityDelta>;

export type GameECSRuntimeConfiguration<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = ECSRuntimeConfiguration<UserSession, Context, UpdateArguments, Actions, Tags, Entity, EntityDelta>;

export type GameECSRuntimeProvider<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = () => GameECSRuntimeConfiguration<UserSession, Context, UpdateArguments>;

export function defineGameECSRuntime<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
>(provider: GameECSRuntimeProvider<UserSession, Context, UpdateArguments>): void {
  defineECSRuntime(provider);
}

export type GameEntitySystem<
  State extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = EntitySystem<State, UpdateArguments, Actions, Tags, Entity, EntityDelta>;

export type GameArchetypeSystem<
  State extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = ArchetypeSystem<State, UpdateArguments, Actions, Tags, Entity, EntityDelta>;

export type GameBehavior<
  State extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = Behavior<State, UpdateArguments, Actions, Tags, Entity, EntityDelta>;

export type GameSystem<
  State extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
> = System<State, UpdateArguments, Actions, Tags, Entity, EntityDelta>;

export function createGameEntitySystem<
  State extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
>(
  execute: GameEntitySystem<State, UpdateArguments>["execute"],
  query: Query | ((buildQuery: QueryBuilder) => QueryBuilder),
): GameEntitySystem<State, UpdateArguments> {
  return createEntitySystem(execute, query);
}

export function createGameArchetypeSystem<
  State extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
>(
  execute: GameArchetypeSystem<State, UpdateArguments>["execute"],
  query: Query | ((buildQuery: QueryBuilder) => QueryBuilder),
): GameArchetypeSystem<State, UpdateArguments> {
  return createArchetypeSystem(execute, query);
}

export function createGameBehavior<
  State extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
>(
  tag: number,
  handler: GameBehavior<State, UpdateArguments>["handler"],
  query: Query | ((buildQuery: QueryBuilder) => QueryBuilder),
  priority?: number,
): GameBehavior<State, UpdateArguments> {
  return createBehavior(tag, handler, query, priority);
}

export function createGameInterestBroadcast<
  UserSession extends {} = {},
  Context extends Record<string, unknown> = {},
  UpdateArguments extends Array<unknown> = [],
>(
  config: Partial<
    InterestBroadcastConfig<
      GameContext<UserSession, Context, UpdateArguments>[0],
      MutationScope,
      Entity,
      EntityDelta
    >
  > = {},
) {
  return createInterestBroadcast<
    GameContext<UserSession, Context, UpdateArguments>[0],
    MutationScope,
    MutationScope,
    Entity,
    EntityDelta
  >({
    encodeBatch: (batch: MutationBatch<Entity, EntityDelta>): Uint8Array =>
      new Uint8Array(
        MutationScope.encode(
          MutationScope({ mutations: batch as unknown as Map<string, MutationRecord> }),
        ),
      ),
    resolveViewer: (record: MutationScope): string | undefined => {
      if (!record.mutations) return undefined;
      for (const key of record.mutations.keys()) return key;
      return undefined;
    },
    ...config,
  });
}
