//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//
//       bebopc version:
//           3.2.3
//
//
//       bebopc source:
//           https://github.com/6over3/bebop
//
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
import { BebopView, BebopRuntimeError, BebopRecord } from "bebop";

export const BEBOP_SCHEMA = new Uint8Array([
  3, 2, 0, 0, 0, 69, 114, 114, 111, 114, 0, 1, 0, 0, 20, 0, 0, 0, 0, 5, 99, 111, 100, 101, 0, 251,
  255, 255, 255, 0, 116, 97, 103, 0, 245, 255, 255, 255, 0, 115, 116, 97, 99, 107, 0, 245, 255, 255,
  255, 0, 109, 115, 103, 0, 245, 255, 255, 255, 0, 100, 101, 116, 97, 105, 108, 115, 0, 241, 255,
  255, 255, 245, 255, 255, 255, 245, 255, 255, 255, 0, 77, 101, 115, 115, 97, 103, 101, 0, 2, 0, 5,
  0, 0, 0, 10, 109, 101, 116, 104, 111, 100, 73, 100, 0, 251, 255, 255, 255, 0, 1, 109, 101, 115,
  115, 97, 103, 101, 73, 100, 0, 244, 255, 255, 255, 0, 2, 116, 105, 109, 101, 115, 116, 97, 109,
  112, 0, 243, 255, 255, 255, 0, 3, 100, 101, 97, 100, 108, 105, 110, 101, 0, 243, 255, 255, 255, 0,
  4, 100, 97, 116, 97, 0, 242, 255, 255, 255, 0, 254, 255, 255, 255, 0, 5, 99, 114, 101, 100, 101,
  110, 116, 105, 97, 108, 0, 245, 255, 255, 255, 0, 6, 115, 116, 97, 116, 117, 115, 0, 254, 255,
  255, 255, 0, 7, 112, 114, 101, 118, 105, 111, 117, 115, 65, 116, 116, 101, 109, 112, 116, 115, 0,
  254, 255, 255, 255, 0, 8, 109, 115, 103, 0, 245, 255, 255, 255, 0, 9, 97, 117, 116, 104, 111, 114,
  105, 122, 97, 116, 105, 111, 110, 0, 245, 255, 255, 255, 0, 10, 0, 0, 0, 0,
]);

export interface Error {
  readonly code: number;

  readonly tag: string;

  readonly stack: string;

  readonly msg: string;

  readonly details: Map<string, string>;
}

export const Error = /*#__PURE__*/ Object.freeze(
  /*#__PURE__*/ Object.assign(
    // Factory function
    (data: Error): Error & BebopRecord => {
      return Object.freeze({
        ...data,
        encode(): Uint8Array {
          return Error.encode(this);
        },
      });
    },
    // Static methods
    {
      encode(record: Error): Uint8Array {
        const view = BebopView.getInstance();
        view.startWriting();
        Error.encodeInto(record, view);
        return view.toArray();
      },

      encodeInto(record: Error, view: BebopView): void {
        view.writeUint32(record.code);
        view.writeString(record.tag);
        view.writeString(record.stack);
        view.writeString(record.msg);
        view.writeUint32(record.details.size);
        for (const [k0, v0] of record.details) {
          view.writeString(k0);
          view.writeString(v0);
        }
      },

      decode(buffer: Uint8Array): Error & BebopRecord {
        const view = BebopView.getInstance();
        view.startReading(buffer);
        const decoded = Error.readFrom(view);
        return Error(decoded);
      },

      readFrom(view: BebopView): Error {
        let field0: number;
        field0 = view.readUint32();
        let field1: string;
        field1 = view.readString();
        let field2: string;
        field2 = view.readString();
        let field3: string;
        field3 = view.readString();
        let field4: Map<string, string>;
        {
          const length0 = view.readUint32();
          field4 = new Map();
          for (let i0 = 0; i0 < length0; i0++) {
            let k0: string;
            let v0: string;
            k0 = view.readString();
            v0 = view.readString();
            field4.set(k0, v0);
          }
        }
        return {
          code: field0,
          tag: field1,
          stack: field2,
          msg: field3,
          details: field4,
        };
      },
    },
  ),
);

export interface Message {
  methodId?: number;

  messageId?: string;

  timestamp?: Date;

  deadline?: Date;

  data?: Uint8Array;

  credential?: string;

  status?: number;

  previousAttempts?: number;

  msg?: string;

  authorization?: string;
}

export const Message = /*#__PURE__*/ Object.freeze(
  /*#__PURE__*/ Object.assign(
    // Factory function
    (data: Message): Message & BebopRecord => {
      return {
        ...data,
        encode(): Uint8Array {
          return Message.encode(this);
        },
      };
    },
    // Static methods
    {
      encode(record: Message): Uint8Array {
        const view = BebopView.getInstance();
        view.startWriting();
        Message.encodeInto(record, view);
        return view.toArray();
      },

      encodeInto(record: Message, view: BebopView): void {
        const pos = view.reserveMessageLength();
        const start = view.length;
        if (record.methodId !== undefined) {
          view.writeByte(1);
          view.writeUint32(record.methodId);
        }
        if (record.messageId !== undefined) {
          view.writeByte(2);
          view.writeGuid(record.messageId);
        }
        if (record.timestamp !== undefined) {
          view.writeByte(3);
          view.writeDate(record.timestamp);
        }
        if (record.deadline !== undefined) {
          view.writeByte(4);
          view.writeDate(record.deadline);
        }
        if (record.data !== undefined) {
          view.writeByte(5);
          view.writeBytes(record.data);
        }
        if (record.credential !== undefined) {
          view.writeByte(6);
          view.writeString(record.credential);
        }
        if (record.status !== undefined) {
          view.writeByte(7);
          view.writeByte(record.status);
        }
        if (record.previousAttempts !== undefined) {
          view.writeByte(8);
          view.writeByte(record.previousAttempts);
        }
        if (record.msg !== undefined) {
          view.writeByte(9);
          view.writeString(record.msg);
        }
        if (record.authorization !== undefined) {
          view.writeByte(10);
          view.writeString(record.authorization);
        }
        view.writeByte(0);
        const end = view.length;
        view.fillMessageLength(pos, end - start);
      },

      decode(buffer: Uint8Array): Message & BebopRecord {
        const view = BebopView.getInstance();
        view.startReading(buffer);
        const decoded = Message.readFrom(view);
        return Message(decoded);
      },

      readFrom(view: BebopView): Message {
        const message: Message = {};
        const length = view.readMessageLength();
        const end = view.index + length;
        while (true) {
          switch (view.readByte()) {
            case 0:
              return message;

            case 1:
              message.methodId = view.readUint32();
              break;

            case 2:
              message.messageId = view.readGuid();
              break;

            case 3:
              message.timestamp = view.readDate();
              break;

            case 4:
              message.deadline = view.readDate();
              break;

            case 5:
              message.data = view.readBytes();
              break;

            case 6:
              message.credential = view.readString();
              break;

            case 7:
              message.status = view.readByte();
              break;

            case 8:
              message.previousAttempts = view.readByte();
              break;

            case 9:
              message.msg = view.readString();
              break;

            case 10:
              message.authorization = view.readString();
              break;

            default:
              view.index = end;
              return message;
          }
        }
      },
    },
  ),
);
