import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { FrameworkConfig, BebopConfig } from "../config/types";
import { loadAndParseSchema, type ParsedSchema } from "./parse-bop";
import { emitComponents } from "./emit-components";
import { emitDelta } from "./emit-delta";
import { emitHelpers, emitHelperImports } from "./emit-helpers";
import { emitFactory } from "./emit-factory";
import { emitClasses } from "./emit-classes";
import { emitGameContext } from "./emit-game-context";
import { emitInterest } from "./emit-interest";
import { emitRuntime } from "./emit-runtime";
import { emitSystems } from "./emit-systems";

export function generate(cwd: string, config: BebopConfig, vampConfig: FrameworkConfig): string {
  // Resolve the generated bebop.ts path from the bebopc config
  const bebopTsPath = resolve(cwd, config.generators?.ts?.outFile ?? "./src/bebop.ts");

  // Parse schema from the generated BEBOP_SCHEMA binary blob
  const schema = loadAndParseSchema(bebopTsPath);

  // Find the Entity message
  const entityDef = schema.definitions.get("Entity");
  if (!entityDef) throw new Error("No 'Entity' definition found in schema");

  // Find the Actions union
  const actionsDef = schema.definitions.get("Actions");
  if (!actionsDef) throw new Error("No 'Actions' definition found in schema");

  // Find the State message
  const stateDef = schema.definitions.get("State");
  if (!stateDef) throw new Error("No 'State' definition found in schema");

  // Find the Tags enum
  const tagsDef = schema.definitions.get("Tags");
  if (!tagsDef) throw new Error("No 'Tags' definition found in schema");

  // Collect imported type names for the bebop import
  const bebopImportTypes = collectBebopImportTypes(entityDef, schema);
  const bebopImport = "./bebop";

  const helperImports = emitHelperImports(entityDef, schema);

  const sections = [
    `// This file is auto-generated by @vamp/cli. Do not edit manually.`,
    `import type { ECSOptions, MutationBatch, EntitySystem, ArchetypeSystem, Behavior, System, Query, QueryBuilder } from "@vamp/ecs";`,
    `import { createEntitySystem, createArchetypeSystem, createBehavior } from "@vamp/ecs";`,
    ...(helperImports ? [helperImports] : []),
    `import { defineECSRuntime, ECSDurableObject, ECSStorage, type ECSRuntimeConfiguration, type RPCContext } from "@vamp/worker";`,
    `import { createInterestBroadcast, type InterestBroadcastConfig } from "@vamp/worker/interest";`,
    `import type { Entity, Actions, Tags${bebopImportTypes} } from "${bebopImport}";`,
    `import { MutationScope, type MutationRecord } from "${bebopImport}";`,
    "",
    emitComponents(entityDef),
    "",
    emitDelta(entityDef, schema),
    "",
    emitHelpers(entityDef, schema),
    "",
    emitFactory(),
    "",
    emitClasses("Tags"),
    "",
    emitGameContext(),
    "",
    emitRuntime(),
    "",
    emitSystems(),
    "",
    emitInterest(),
    "",
  ];

  const output = sections.join("\n");
  const outPath = resolve(cwd, vampConfig.outFile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, output, "utf-8");
  return outPath;
}

/** Candidate custom type names a field references (base, array member, or map value). */
function candidateTypeNames(field: any): string[] {
  if (field.isArray) return field.memberTypeName ? [field.memberTypeName] : [];
  if (field.isMap) return field.valueTypeName ? [field.valueTypeName] : [];
  return [field.typeName];
}

function collectBebopImportTypes(entityDef: any, schema: ParsedSchema): string {
  const types = new Set<string>();
  for (const field of entityDef.fields) {
    for (const typeName of candidateTypeNames(field)) {
      const def = schema.definitions.get(typeName);
      if (
        def &&
        def.name !== "Entity" &&
        def.name !== "Actions" &&
        def.name !== "State" &&
        def.name !== "Tags"
      ) {
        const deltaName = `${def.name}Delta`;
        if (schema.definitions.has(deltaName)) {
          // Only import the delta type — base type is used implicitly via Entity
          types.add(deltaName);
        } else {
          types.add(def.name);
        }
      }
    }
  }
  if (types.size === 0) return "";
  return ", " + [...types].join(", ");
}
