import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import type { FrameworkConfig, BebopConfig } from "../config/types";
import { loadAndParseSchema, type ParsedSchema } from "./parse-bop";
import { emitComponents } from "./emit-components";
import { emitDelta } from "./emit-delta";
import { emitHelpers, emitHelperImports } from "./emit-helpers";
import { emitFactory } from "./emit-factory";
import { emitClasses } from "./emit-classes";
import { emitGameContext } from "./emit-game-context";
import { emitInterest } from "./emit-interest";
import { emitRuntime } from "./emit-runtime";
import { emitSystems } from "./emit-systems";

/** Absolute paths of the three files `generate` writes. */
export interface GeneratedPaths {
  /** Backward-compatible barrel re-exporting `core` + `worker`. */
  barrel: string;
  /** Pure ECS file (`@vampgg/ecs` only) — safe to import from non-Worker code. */
  core: string;
  /** Worker runtime file (`@vampgg/worker`, imports `cloudflare:workers`). */
  worker: string;
}

const AUTOGEN_HEADER = `// This file is auto-generated by @vampgg/cli. Do not edit manually.`;

/**
 * Derive a `.core`/`.worker` sibling path from the barrel `outFile`
 * (`./src/game.generated.ts` → `./src/game.core.generated.ts`). Falls back to
 * inserting the part before a plain `.ts`, or appending it, for atypical names.
 */
function derivePartPath(outFile: string, part: "core" | "worker"): string {
  if (outFile.endsWith(".generated.ts")) {
    return `${outFile.slice(0, -".generated.ts".length)}.${part}.generated.ts`;
  }
  if (outFile.endsWith(".ts")) {
    return `${outFile.slice(0, -".ts".length)}.${part}.ts`;
  }
  return `${outFile}.${part}.ts`;
}

/**
 * Build the relative ESM specifier that imports `toFile` from `fromFile`, with a
 * `.js` extension (nodenext-compatible; maps back to the `.ts` source).
 */
function relativeImport(fromFile: string, toFile: string): string {
  let rel = relative(dirname(fromFile), toFile).split("\\").join("/");
  rel = rel.replace(/\.ts$/, ".js");
  return rel.startsWith(".") ? rel : `./${rel}`;
}

function writeGenerated(path: string, sections: string[]): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, sections.join("\n"), "utf-8");
}

export function generate(
  cwd: string,
  config: BebopConfig,
  vampConfig: FrameworkConfig,
): GeneratedPaths {
  // Resolve the generated bebop.ts path from the bebopc config
  const bebopTsPath = resolve(cwd, config.generators?.ts?.outFile ?? "./src/bebop.ts");

  // Parse schema from the generated BEBOP_SCHEMA binary blob
  const schema = loadAndParseSchema(bebopTsPath);

  // Find the Entity message
  const entityDef = schema.definitions.get("Entity");
  if (!entityDef) throw new Error("No 'Entity' definition found in schema");

  // Find the Actions union
  const actionsDef = schema.definitions.get("Actions");
  if (!actionsDef) throw new Error("No 'Actions' definition found in schema");

  // Find the State message
  const stateDef = schema.definitions.get("State");
  if (!stateDef) throw new Error("No 'State' definition found in schema");

  // Find the Tags enum
  const tagsDef = schema.definitions.get("Tags");
  if (!tagsDef) throw new Error("No 'Tags' definition found in schema");

  // Collect imported type names for the bebop import
  const bebopImportTypes = collectBebopImportTypes(entityDef, schema);
  // Emit an explicit `.js` extension so the specifier resolves under both
  // `moduleResolution: nodenext` (ESM requires the extension; it maps `.js`→`.ts`)
  // and `bundler`. Extensionless would only work under bundler resolution.
  const bebopImport = "./bebop.js";

  const helperImports = emitHelperImports(entityDef, schema);

  // The output is split into a pure ECS file and a Worker-runtime file, with a
  // backward-compatible barrel re-exporting both. Non-Worker packages import the
  // core file directly to keep `@vampgg/worker` (and its `cloudflare:workers`
  // import) out of their dependency graph.
  const barrelPath = resolve(cwd, vampConfig.outFile);
  const corePath = resolve(
    cwd,
    vampConfig.coreOutFile ?? derivePartPath(vampConfig.outFile, "core"),
  );
  const workerPath = resolve(
    cwd,
    vampConfig.workerOutFile ?? derivePartPath(vampConfig.outFile, "worker"),
  );

  // --- Core (pure): only `@vampgg/ecs` + `./bebop`. ---
  const coreSections = [
    AUTOGEN_HEADER,
    `import type { ECSOptions, EntitySystem, ArchetypeSystem, Behavior, System, Query, QueryBuilder } from "@vampgg/ecs";`,
    `import { createEntitySystem, createArchetypeSystem, createBehavior } from "@vampgg/ecs";`,
    ...(helperImports ? [helperImports] : []),
    `import type { Entity, Actions, Tags${bebopImportTypes} } from "${bebopImport}";`,
    "",
    emitComponents(entityDef),
    "",
    emitDelta(entityDef, schema),
    "",
    emitHelpers(entityDef, schema),
    "",
    emitFactory(),
    "",
    emitSystems(),
    "",
  ];

  // --- Worker: the DO/runtime/interest, depends on `@vampgg/worker`. Imports the
  //     ergonomic `EntityDelta` type from the core file. ---
  const coreFromWorker = relativeImport(workerPath, corePath);
  const workerSections = [
    AUTOGEN_HEADER,
    `import type { MutationBatch } from "@vampgg/ecs";`,
    `import { defineECSRuntime, ECSDurableObject, ECSStorage, type ECSRuntimeConfiguration, type RPCContext } from "@vampgg/worker";`,
    `import { createInterestBroadcast, type InterestBroadcastConfig } from "@vampgg/worker/interest";`,
    `import type { Entity, Actions, Tags } from "${bebopImport}";`,
    `import { MutationScope, type MutationRecord } from "${bebopImport}";`,
    `import type { EntityDelta } from "${coreFromWorker}";`,
    "",
    emitClasses("Tags", vampConfig.env),
    "",
    emitGameContext(),
    "",
    emitRuntime(),
    "",
    emitInterest(),
    "",
  ];

  // --- Barrel: re-export both so existing `./game.generated` imports keep working. ---
  const coreFromBarrel = relativeImport(barrelPath, corePath);
  const workerFromBarrel = relativeImport(barrelPath, workerPath);
  const barrelSections = [
    AUTOGEN_HEADER,
    `// Barrel over the generated ECS surface. Import the pure core file directly`,
    `// (\`${coreFromBarrel}\`) from non-Worker code to avoid pulling in @vampgg/worker`,
    `// and its \`cloudflare:workers\` import.`,
    `export * from "${coreFromBarrel}";`,
    `export * from "${workerFromBarrel}";`,
    "",
  ];

  writeGenerated(corePath, coreSections);
  writeGenerated(workerPath, workerSections);
  writeGenerated(barrelPath, barrelSections);

  return { barrel: barrelPath, core: corePath, worker: workerPath };
}

/** Candidate custom type names a field references (base, array member, or map value). */
function candidateTypeNames(field: any): string[] {
  if (field.isArray) return field.memberTypeName ? [field.memberTypeName] : [];
  if (field.isMap) return field.valueTypeName ? [field.valueTypeName] : [];
  return [field.typeName];
}

function collectBebopImportTypes(entityDef: any, schema: ParsedSchema): string {
  const types = new Set<string>();
  for (const field of entityDef.fields) {
    for (const typeName of candidateTypeNames(field)) {
      const def = schema.definitions.get(typeName);
      if (
        def &&
        def.name !== "Entity" &&
        def.name !== "Actions" &&
        def.name !== "State" &&
        def.name !== "Tags"
      ) {
        const deltaName = `${def.name}Delta`;
        if (schema.definitions.has(deltaName)) {
          // Only import the delta type — base type is used implicitly via Entity
          types.add(deltaName);
        } else {
          types.add(def.name);
        }
      }
    }
  }
  if (types.size === 0) return "";
  return ", " + [...types].join(", ");
}
