import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { FrameworkConfig, BebopConfig } from "../config/types";
import { loadAndParseSchema, type ParsedSchema } from "./parse-bop";
import { emitComponents } from "./emit-components";
import { emitDelta } from "./emit-delta";
import { emitHelpers } from "./emit-helpers";
import { emitFactory } from "./emit-factory";
import { emitClasses } from "./emit-classes";

export function generate(
  cwd: string,
  config: BebopConfig,
  frameworkConfig: FrameworkConfig,
): string {
  // Resolve the generated bebop.ts path from the bebopc config
  const bebopTsPath = resolve(cwd, config.generators?.ts?.outFile ?? "./src/bebop.ts");

  // Parse schema from the generated BEBOP_SCHEMA binary blob
  const schema = loadAndParseSchema(bebopTsPath);

  // Find the Entity message
  const entityDef = schema.definitions.get("Entity");
  if (!entityDef) throw new Error("No 'Entity' definition found in schema");

  // Find the Actions union
  const actionsDef = schema.definitions.get("Actions");
  if (!actionsDef) throw new Error("No 'Actions' definition found in schema");

  // Find the State message
  const stateDef = schema.definitions.get("State");
  if (!stateDef) throw new Error("No 'State' definition found in schema");

  // Collect imported type names for the bebop import
  const bebopImportTypes = collectBebopImportTypes(entityDef, schema);
  const bebopImport = "./bebop";

  const sections = [
    `// This file is auto-generated by @framework/config. Do not edit manually.`,
    `import type { ECSOptions } from "@framework/ecs";`,
    `import { ECSDurableObject, Entities } from "@framework/worker";`,
    `import type { Entity, Actions, State${bebopImportTypes} } from "${bebopImport}";`,
    "",
    emitComponents(entityDef),
    "",
    emitDelta(entityDef, schema),
    "",
    emitHelpers(entityDef, schema),
    "",
    emitFactory(),
    "",
    emitClasses(),
    "",
  ];

  const output = sections.join("\n");
  const outPath = resolve(cwd, frameworkConfig.outFile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, output, "utf-8");
  return outPath;
}

function collectBebopImportTypes(entityDef: any, schema: ParsedSchema): string {
  const types = new Set<string>();
  for (const field of entityDef.fields) {
    if (!field.isArray && !field.isMap) {
      // Non-scalar custom type — need to import it
      const def = schema.definitions.get(field.typeName);
      if (def && def.name !== "Entity" && def.name !== "Actions" && def.name !== "State") {
        types.add(def.name);
        // Also import delta type if it exists
        const deltaName = `${def.name}Delta`;
        if (schema.definitions.has(deltaName)) {
          types.add(deltaName);
        }
      }
    }
  }
  if (types.size === 0) return "";
  return ", " + [...types].join(", ");
}
