import type { SourceField, SourceMessage } from "./parse-bop-source";

const HEADER = `// AUTO-GENERATED by @vamp/config. Do not edit manually.
// Regenerated from the Entity message on every \`config generate\`.`;

function capitalize(name: string): string {
  return name.length === 0 ? name : name[0].toUpperCase() + name.slice(1);
}

/** Message name for a per-member-type array delta (e.g. "guid" -> "GuidArrayDelta"). */
function arrayDeltaName(memberType: string): string {
  return `${capitalize(memberType)}ArrayDelta`;
}

/**
 * Resolve the bebop delta type for an Entity field. Mirrors the TS delta
 * mapping in emit-delta.ts so the bebop wire type stays structurally aligned
 * with the in-memory TS EntityDelta type.
 */
function deltaTypeForField(field: SourceField): string {
  // tags is last-write-wins (keep the raw `Tags[]` shape).
  if (field.name === "tags") return field.rawType;

  if (field.isArray) {
    // Scalar element arrays use a CRDT-style array delta message.
    if (field.isScalar) return arrayDeltaName(field.memberType!);
    // Non-scalar element arrays fall back to last-write-wins.
    return field.rawType;
  }

  // Maps are last-write-wins.
  if (field.isMap) return field.rawType;

  // Scalars are last-write-wins.
  if (field.isScalar) return field.typeName;

  // Custom message/struct fields use the `<Type>Delta` naming convention.
  return `${field.typeName}Delta`;
}

/** Collect the distinct scalar-array member types that need a delta message. */
function collectArrayDeltaMembers(entity: SourceMessage): string[] {
  const members = new Set<string>();
  for (const field of entity.fields) {
    if (field.name === "tags") continue;
    if (field.isArray && field.isScalar) members.add(field.memberType!);
  }
  return [...members];
}

function emitArrayDeltaMessage(memberType: string): string {
  return `message ${arrayDeltaName(memberType)} {
  1 -> ${memberType}[] set;
  2 -> ${memberType}[] add;
  3 -> ${memberType}[] remove;
}`;
}

function emitEntityDelta(entity: SourceMessage): string {
  const fields = entity.fields
    .map((f) => `  ${f.index} -> ${deltaTypeForField(f)} ${f.name};`)
    .join("\n");
  return `message EntityDelta {\n${fields}\n}`;
}

const MUTATION_TYPE = `enum MutationType {
  Insert = 1;
  Update = 2;
  Delete = 3;
}`;

const MUTATION_RECORD = `union MutationRecord {
  1 -> struct Insert {
    Entity entity;
  }
  2 -> struct Update {
    EntityDelta delta;
  }
  3 -> struct Delete {
    Entity entity;
  }
}`;

const MUTATION_SCOPE = `message MutationScope {
  1 -> map[guid, MutationRecord] mutations;
}`;

/**
 * Emit the bebop schema providing serializable EntityDelta + MutationScope
 * types, derived from the Entity message.
 *
 * @param entity Parsed Entity message.
 * @param entityImportPath Import path to the entity schema, relative to the
 *   emitted file (e.g. "./entity.bop").
 */
export function emitMutationSchema(entity: SourceMessage, entityImportPath: string): string {
  const sections: string[] = [HEADER, `import "${entityImportPath}"`];

  for (const member of collectArrayDeltaMembers(entity)) {
    sections.push(emitArrayDeltaMessage(member));
  }

  sections.push(emitEntityDelta(entity), MUTATION_TYPE, MUTATION_RECORD, MUTATION_SCOPE);

  return sections.join("\n\n") + "\n";
}
