import { describe, expect, it } from "vite-plus/test";
import { emitMutationSchema } from "../src/generators/emit-mutation-bop.js";
import { parseEntityMessage } from "../src/generators/parse-bop-source.js";

const ENTITY_SOURCE = `import "../node_modules/@vampgg/utils/schema/pool.bop"
import "./tags.bop"

message Entity {
\t1 -> guid id;
\t2 -> guid sk;
\t3 -> Tags[] tags;
\t4 -> guid parent;
\t5 -> guid[] children;
\t6 -> Pool health;
}
`;

function generate(): string {
  // PoolDelta is user-supplied (via the imported pool.bop), so reuse it verbatim.
  return emitMutationSchema(
    parseEntityMessage(ENTITY_SOURCE),
    "./entity.bop",
    new Set(["PoolDelta"]),
  );
}

describe("emitMutationSchema", () => {
  it("imports the entity schema", () => {
    expect(generate()).toContain(`import "./entity.bop"`);
  });

  it("emits a scalar-array delta message for children's member type", () => {
    const out = generate();
    expect(out).toContain("message GuidArrayDelta {");
    expect(out).toContain("1 -> guid[] set;");
    expect(out).toContain("2 -> guid[] add;");
    expect(out).toContain("3 -> guid[] remove;");
  });

  it("emits EntityDelta preserving Entity field indices", () => {
    const out = generate();
    expect(out).toContain("message EntityDelta {");
    expect(out).toContain("1 -> guid id;");
    expect(out).toContain("2 -> guid sk;");
    // tags is last-write-wins
    expect(out).toContain("3 -> Tags[] tags;");
    expect(out).toContain("4 -> guid parent;");
    // scalar array -> array delta message
    expect(out).toContain("5 -> GuidArrayDelta children;");
    // custom message -> <Type>Delta convention
    expect(out).toContain("6 -> PoolDelta health;");
  });

  it("emits the MutationType enum", () => {
    const out = generate();
    expect(out).toContain("enum MutationType {");
    expect(out).toContain("Insert = 1;");
    expect(out).toContain("Update = 2;");
    expect(out).toContain("Delete = 3;");
  });

  it("emits the MutationRecord union mirroring ecs types", () => {
    const out = generate();
    expect(out).toContain("union MutationRecord {");
    expect(out).toContain("1 -> struct Insert {");
    expect(out).toContain("Entity entity;");
    expect(out).toContain("2 -> struct Update {");
    expect(out).toContain("EntityDelta delta;");
    expect(out).toContain("3 -> struct Delete {");
  });

  it("emits the MutationScope message keyed by guid", () => {
    expect(generate()).toContain("1 -> map[guid, MutationRecord] mutations;");
  });

  it("marks the file as auto-generated", () => {
    expect(generate()).toContain("AUTO-GENERATED by @vampgg/cli");
  });
});
